# Generated by Django 5.2.4 on 2025-07-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_options_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('published', 'Published')], default='draft', max_length=100),
        ),
    ]
